language: python
python:
  - 3.7.2
  - pypy3
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
install:
  - make dist
  - pip install dist/scraping_toolbox-*.whl
script:
  - make test
